...

diff --git a/lib/util b/lib/util
--- a/lib/util
+++ b/lib/util
@@ -1,6 +1,19 @@
+
 ___x_cmd_wx_run(){
-    : cd
-    x ws run
+    local wxfile="${1:?Provide wx file}"; shift
+    local ___X_CMD_WX_RUN_OLD_PWD="$PWD"
+
+    ___x_cmd_wx_unpkg "$wxfile" || return
+    if ! cd "$___X_CMD_WX_UNPKG_DIR"; then
+        x:error "Cannot access folder: $___X_CMD_WX_UNPKG_DIR"
+        return 1
+    fi
+
+    x ws run "$@"
+
+    if ! cd "$___X_CMD_WX_RUN_OLD_PWD"; then
+        x:error "Cannot return to original folder: $___X_CMD_WX_RUN_OLD_PWD"
+    fi
 }
 
 ___x_cmd_wx_pkg(){
