...

diff --git a/lib/util b/lib/util
--- a/lib/util
+++ b/lib/util
@@ -15,15 +15,19 @@ ___x_cmd_wx_run(){
         return 1
     fi
 
-    if [ -f ".x-cmd/installed_already" ] && ! x ws installed_already; then
-        x ws install || {
-            local exit=$?
-            x:error "Exit=$exit: Installation failure."
-            return "$exit"
-        }
+    if [ -f ".x-cmd/dist-run" ]; then
+        x ws run-dist "$@"
+        return
+    else
+        if [ -f ".x-cmd/installed_already" ] && ! x ws installed_already; then
+            if ! x ws install; then
+                local exit=$?
+                x:error "Exit=$exit: Installation failure."
+                return "$exit"
+            fi
+        fi
+        x ws run "$@"
     fi
-
-    x ws run "$@"
 
     if ! cd "$___X_CMD_WX_RUN_OLD_PWD"; then
         x:error "Cannot return to original folder: $___X_CMD_WX_RUN_OLD_PWD"
